# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - apt-get update
    - apt-get -y install libopenmpi-dev
    - export OMPI_ALLOW_RUN_AS_ROOT=1
    - export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    - pip install ".[dev]"
    - make BUILDDIR=$READTHEDOCS_OUTPUT docs
