[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "pytest-isolate"
description = ''
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE.md"}
version = "0.1.0"
keywords = []
authors = [
  { name = "gilfree", email = "gilfree@users.noreply.github.com" },
]

[project.entry-points.pytest11]
pytest_isolate = "pytest_isolate_mpi.plugin"
