[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "pytest-isolate"
description = ''
readme = "README.md"
requires-python = ">=3.7"
license = "BSD"
keywords = []
authors = [
  { name = "gilfree", email = "gilfree@users.noreply.github.com" },
]
